### ISSUE TITLE
Some way to filter by team

### ISSUE THREAD

**Issue by mvdan** [protocol/web3-dev-team#26]
Right now we have over twenty open PRs, so it's hard to tell which ones are from what team unless one memorizes who is in what team :)

Assuming that each project is written by (and will be implemented by) a single team, should we label them as such? Either as a PR label or as a somewhat-machine-readable field in the markdown file, or maybe both.

Even if some projects might span multiple teams, I still imagine that most projects will clearly fit within a single project team's scope.

**Comment by raulk** [comment]
How about labels of the kind?

* `Proposer: <Team>`
* `Implementor: <Team>`

Status labels would also make sense.

**Comment by mvdan** [comment]
Sounds good with me - as long as the team names are consistent between files forever, to make grepping/filtering easier.

**Comment by momack2** [comment]
I like this idea! @mikeal can you help implement this labeling based on who the PR author is?

**Comment by anorth** [comment]
> hard to tell which ones are from what team

I don't think it's a desirable property that you can tell which proposals are from which team. IMO where the proposal came from is of very little importance to deciding what to do with it. I consider it a bit of a bug / cold start problem that, at present, most proposals are authored by people expecting/hoping to implement them themselves, and teams are not paying much attention to proposals originating elsewhere. Tags might only make it more clear "which ones I can ignore".

Other people who might author proposals include:
- PMs, EMs myself, and other people on our broader team but not embedded with a project team
- members of ecosystem teams
- individuals who are quietly watching and observing, and might better see the forest rather than trees

I would not want to make such proposals harder to gain attention.

That said, I wouldn't oppose some labelling about the area, the general thrust or direction with with a project aligns. These currently map very roughly to project team focus areas, but I wouldn't want to lock that in.

I think labels on GitHub for the PRs and tracking issues would make a great lightweight mechanism for something like that: real-time, low overhead, filtering built-in.

**Comment by mikeal** [comment]
For “labels by area,” what would the list of labels be? Teams are obvious but we don’t have a list of subject areas that I’m aware of.

**Comment by anorth** [comment]
As an example (please improve it, and also if we use a flexible mechanism we can change them later):
- Protocol Functionality
- APIs
- Tooling
- Metrics
- Proof of Concept / Use cases
- Docs & Specs

**Comment by momack2** [comment]
We now have "Nitro", "Bedrock", and will have another label for something like "maintainership backlog". I think that's sufficient here and we can use assignee for filtering who on what
