### ISSUE TITLE
Feature request: team roster in README

### ISSUE THREAD

**Issue by mikeal** [protocol/web3-dev-team#41]
Could we get a team roster in the README with everyone’s github usernames?

Any concerns with this being public?

**Comment by galargh** [comment]
Would you say this issue is still valid? If so, who would we want to be listed here? Just FYI, now we have a way to look up GitHub usernames for more specific teams, e.g. if I wanted to know who is currently maintaining Kubo, I could check the list in https://github.com/ipfs/github-mgmt/blob/f3e85823420ea82e707cf6680f1ceb9ef3ef18a7/github/ipfs.yml#L5696

I'm going to close it for now but feel free to reopen if it is still valid 🙇
